# Generated by Django 5.1.5 on 2025-01-21 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_avatar_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('manager', 'Manager'), ('doctor', 'Doctor')], default='user', max_length=10, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100, verbose_name='specialization')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='experience')),
                ('location', models.CharField(max_length=150, verbose_name='location')),
                ('clinic_name', models.CharField(max_length=150, verbose_name='clinic name')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='consultation fee')),
                ('is_consultation_free', models.BooleanField(default=False, verbose_name='is_consultation_free')),
                ('availability_today', models.BooleanField(default=False, verbose_name='availability today')),
                ('rating_percentage', models.PositiveIntegerField(default=0, verbose_name='rating percentage')),
                ('patient_stories', models.PositiveIntegerField(default=0, verbose_name='patient stories')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('image', models.ImageField(upload_to='news/', verbose_name='image')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created_at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
