# Generated by Django 5.1.5 on 2025-02-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_date_delete_booking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='date',
            unique_together={('doctor', 'date', 'time')},
        ),
    ]
